name: very_good_analysis
version: 1.0.0
description: >-
  Very Good Dart analyzer settings and best practices used internally at Very Good Ventures.
homepage: https://github.com/VGVentures/very_good_code/very_good_analysis

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  pedantic: ^1.0.0